// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/applications" | "/contact" | "/login" | "/operator" | "/operator/seat-map" | "/register" | "/reservation" | "/reservation/status" | "/reset-password" | "/route"
type AppRouteHandlerRoutes = "/api/admin/applications/status" | "/api/admin/notifications" | "/api/admin/operators" | "/api/admin/overview" | "/api/admin/reports" | "/api/admin/reservations" | "/api/admin/seats" | "/api/auth/forgot-password" | "/api/auth/resolve-redirect" | "/api/contact" | "/api/create-checkout" | "/api/operator/chat/conversations" | "/api/operator/chat/unread" | "/api/operator/notifications" | "/api/operator/passengers" | "/api/operator/payments" | "/api/operator/reservations" | "/api/operator/reservations/chat" | "/api/operator/reservations/status" | "/api/operator/seats" | "/api/payments" | "/api/paymongo/webhook" | "/api/public/route-metrics" | "/api/public/routes-fares" | "/api/queue/active" | "/api/queue/apply" | "/api/reservations/chat" | "/api/reservations/intent" | "/api/reservations/mark-paid" | "/api/reservations/seats" | "/api/reservations/status" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/applications": {}
  "/api/admin/applications/status": {}
  "/api/admin/notifications": {}
  "/api/admin/operators": {}
  "/api/admin/overview": {}
  "/api/admin/reports": {}
  "/api/admin/reservations": {}
  "/api/admin/seats": {}
  "/api/auth/forgot-password": {}
  "/api/auth/resolve-redirect": {}
  "/api/contact": {}
  "/api/create-checkout": {}
  "/api/operator/chat/conversations": {}
  "/api/operator/chat/unread": {}
  "/api/operator/notifications": {}
  "/api/operator/passengers": {}
  "/api/operator/payments": {}
  "/api/operator/reservations": {}
  "/api/operator/reservations/chat": {}
  "/api/operator/reservations/status": {}
  "/api/operator/seats": {}
  "/api/payments": {}
  "/api/paymongo/webhook": {}
  "/api/public/route-metrics": {}
  "/api/public/routes-fares": {}
  "/api/queue/active": {}
  "/api/queue/apply": {}
  "/api/reservations/chat": {}
  "/api/reservations/intent": {}
  "/api/reservations/mark-paid": {}
  "/api/reservations/seats": {}
  "/api/reservations/status": {}
  "/auth/callback": {}
  "/contact": {}
  "/login": {}
  "/operator": {}
  "/operator/seat-map": {}
  "/register": {}
  "/reservation": {}
  "/reservation/status": {}
  "/reset-password": {}
  "/route": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
