// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/(public)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(public)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/reservation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reservation">> = Specific
  const handler = {} as typeof import("../../app/(public)/reservation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/reservation/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reservation/status">> = Specific
  const handler = {} as typeof import("../../app/(public)/reservation/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/route/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/route">> = Specific
  const handler = {} as typeof import("../../app/(public)/route/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/applications">> = Specific
  const handler = {} as typeof import("../../app/admin/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/operator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operator">> = Specific
  const handler = {} as typeof import("../../app/operator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/operator/seat-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operator/seat-map">> = Specific
  const handler = {} as typeof import("../../app/operator/seat-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/applications/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/applications/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/admin/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/operators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/operators">> = Specific
  const handler = {} as typeof import("../../app/api/admin/operators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/overview">> = Specific
  const handler = {} as typeof import("../../app/api/admin/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reservations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/seats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seats">> = Specific
  const handler = {} as typeof import("../../app/api/admin/seats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/resolve-redirect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resolve-redirect">> = Specific
  const handler = {} as typeof import("../../app/api/auth/resolve-redirect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/create-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-checkout">> = Specific
  const handler = {} as typeof import("../../app/api/create-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/chat/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/chat/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/operator/chat/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/chat/unread/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/chat/unread">> = Specific
  const handler = {} as typeof import("../../app/api/operator/chat/unread/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/operator/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/passengers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/passengers">> = Specific
  const handler = {} as typeof import("../../app/api/operator/passengers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/payments">> = Specific
  const handler = {} as typeof import("../../app/api/operator/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/reservations/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/reservations/chat">> = Specific
  const handler = {} as typeof import("../../app/api/operator/reservations/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/reservations">> = Specific
  const handler = {} as typeof import("../../app/api/operator/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/reservations/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/reservations/status">> = Specific
  const handler = {} as typeof import("../../app/api/operator/reservations/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operator/seats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operator/seats">> = Specific
  const handler = {} as typeof import("../../app/api/operator/seats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments">> = Specific
  const handler = {} as typeof import("../../app/api/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/paymongo/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paymongo/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/paymongo/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/route-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/route-metrics">> = Specific
  const handler = {} as typeof import("../../app/api/public/route-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/routes-fares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/routes-fares">> = Specific
  const handler = {} as typeof import("../../app/api/public/routes-fares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/queue/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/active">> = Specific
  const handler = {} as typeof import("../../app/api/queue/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/queue/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/apply">> = Specific
  const handler = {} as typeof import("../../app/api/queue/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/chat">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/intent">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/mark-paid/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/mark-paid">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/mark-paid/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/seats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/seats">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/seats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/status">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
